// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTYx4fl7CqirCtcdynhaIwzt-29nHh1KU',
    appId: '1:529330932738:web:9e6ac5408686773868eb1b',
    messagingSenderId: '529330932738',
    projectId: 'rxdart-contact-app',
    authDomain: 'rxdart-contact-app.firebaseapp.com',
    storageBucket: 'rxdart-contact-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxGRmygd1OVb01ycCrSSgSNIibMiutV4A',
    appId: '1:529330932738:android:8c182492505a1efc68eb1b',
    messagingSenderId: '529330932738',
    projectId: 'rxdart-contact-app',
    storageBucket: 'rxdart-contact-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzxklbru33L0xGqVGETBxfypqhlX1cgz4',
    appId: '1:529330932738:ios:55b478ca1774b7f568eb1b',
    messagingSenderId: '529330932738',
    projectId: 'rxdart-contact-app',
    storageBucket: 'rxdart-contact-app.appspot.com',
    iosBundleId: 'com.umair.shaik.rxdartHandsOn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzxklbru33L0xGqVGETBxfypqhlX1cgz4',
    appId: '1:529330932738:ios:9251d1bd480dd7e268eb1b',
    messagingSenderId: '529330932738',
    projectId: 'rxdart-contact-app',
    storageBucket: 'rxdart-contact-app.appspot.com',
    iosBundleId: 'com.umair.shaik.rxdartHandsOn.RunnerTests',
  );
}
